/// <reference types="astro/client" />

// Cloudflare runtime binding types (DB, secrets) are generated by `pnpm cf-typegen`
// into worker-configuration.d.ts once bindings exist (Phase 3). Access bindings via
// `import { env } from "cloudflare:workers"` and the execution context via
// `Astro.locals.cfContext` (Astro 6 / @astrojs/cloudflare v13).
