/// <reference types="astro/client" />
/// <reference path="../worker-configuration.d.ts" />

// Binding/var types (DB, OWNER_EMAIL) are generated by `pnpm cf-typegen` into
// worker-configuration.d.ts. Access bindings via `import { env } from "cloudflare:workers"`
// and the execution context via `Astro.locals.cfContext` (Astro 6 / adapter v13).
//
// Secrets are NOT in wrangler.jsonc (they live in .dev.vars / `wrangler secret put`),
// so cf-typegen can't see them. Declare them here so `env.*` stays typed. Optional
// because they may be unset locally (the API degrades gracefully when they are).
declare namespace Cloudflare {
  interface Env {
    RESEND_API_KEY?: string;
    TURNSTILE_SECRET_KEY?: string;
  }
}
